#Spring 
spring:
  datasource:
    password: elza2017    
    url: jdbc:postgresql://localhost:5432/tourhost-db
    username: postgres
  jpa:
    generate-ddl: true
    
  application:
     name: tourhost-service
     
  resources:
    chain:
      enabled: true     
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9091/eureka

# HTTP Server
server:
  port: 8090  
 
security:
  basic:
    enable: true   
     
jwt:
  header: Authorization
  secret: NWT-TourDeBosna

    
    