#Spring 
spring:
  datasource:
    password: 123
    url: jdbc:postgresql://postgres-db:5432/postgres
    username: postgres
  jpa:
    generate-ddl: true
    
  application:
     name: tourhost-service     
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9091

# HTTP Server
server:
  port: 8090  
 
security:
  basic:
    enable: false   
    