#Spring 
spring:
  datasource:
    password: elza2017
    url: jdbc:postgresql://localhost/tour-host
    username: postgres
  jpa:
    generate-ddl: true
    
  application:
     name: tourhost-service
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

# HTTP Server
server:
  port: 8090  
 
  
security:
  basic:
    enable: false   
    